### ISSUE TITLE
Email on failure only

### ISSUE THREAD

**Issue by v1peractual** [ncsa/puppet-profile_backup#9] opened 2023-08-18 13:21 UTC
I would like to implement an option to email on failure only. Since we have monitoring of backups (of lack of backups) in Telegraf, the crons should be sent to dev null and an admin email address (sourced from the email profile) should email if the backup failed and the output of the failure.

**Comment by billglick** [comment] 2024-02-29 17:35
This is a duplicate of #10

**Comment by billglick** [comment] 2024-02-29 17:38
https://github.com/ncsa/puppet-profile_backup/blob/365cf189f4c9a6541bb90351725d884743999ed5/manifests/client.pp#L181-L191

Currently each cron run creates an email to root by default. Need way to not do that and/or only do so if an error.

**Closed as completed** 2024-05-02 16:01 UTC
